<?php

namespace App\Services;

use App\Models\DnsRecord;
use App\Models\Domain;
use App\Models\Setting;
use Symfony\Component\Process\Process;

/**
 * DnsZoneSyncService
 * 
 * Writes BIND-compatible zone files to /etc/bind/zones/{domain}.db,
 * registers zones in /etc/bind/named.conf.local, and reloads BIND.
 * 
 * Called automatically when DNS records are created, updated, or deleted.
 */
class DnsZoneSyncService
{
    private string $zoneDir = '/etc/bind/zones';
    private string $namedConfLocal = '/etc/bind/named.conf.local';

    /**
     * Get configured nameservers from settings table
     */
    private function getNameservers(): array
    {
        $ns1 = Setting::where('key', 'nameserver_1')->value('value')
            ?? Setting::where('key', 'ns1')->value('value')
            ?? 'ns1.node1.qiwhost.com';
        $ns2 = Setting::where('key', 'nameserver_2')->value('value')
            ?? Setting::where('key', 'ns2')->value('value')
            ?? 'ns2.node1.qiwhost.com';

        return [$ns1, $ns2];
    }

    /**
     * Get server IP from settings or system
     */
    private function getServerIp(): string
    {
        if (file_exists('/etc/qiwhost/server_ip')) {
            $ip = trim(file_get_contents('/etc/qiwhost/server_ip'));
            if (!empty($ip)) return $ip;
        }

        $ip = Setting::where('key', 'server_ip')->value('value');
        if (!empty($ip)) return $ip;

        try {
            $ip = trim(shell_exec("hostname -I | awk '{print $1}'") ?? '');
            if (!empty($ip)) return $ip;
        } catch (\Exception $e) {}

        return '127.0.0.1';
    }

    /**
     * Generate auto-incrementing SOA serial (YYYYMMDDnn format)
     */
    private function generateSerial(string $domainName): string
    {
        $dateBase = date('Ymd');
        $zoneFile = "{$this->zoneDir}/{$domainName}.db";

        // Try to read current serial from existing zone file
        if (file_exists($zoneFile)) {
            try {
                $content = file_get_contents($zoneFile);
                if (preg_match('/(\d{10})\s*;\s*Serial/', $content, $matches)) {
                    $currentSerial = $matches[1];
                    $currentDate = substr($currentSerial, 0, 8);
                    $currentSeq = (int) substr($currentSerial, 8, 2);

                    if ($currentDate === $dateBase) {
                        // Same day, increment sequence
                        return $dateBase . str_pad($currentSeq + 1, 2, '0', STR_PAD_LEFT);
                    }
                }
            } catch (\Exception $e) {}
        }

        return $dateBase . '01';
    }

    /**
     * Compile a BIND-compatible zone file for a domain
     */
    public function compileZoneFile(Domain $domain): string
    {
        [$ns1, $ns2] = $this->getNameservers();
        $ns1Fqdn = rtrim($ns1, '.') . '.';
        $ns2Fqdn = rtrim($ns2, '.') . '.';

        // SOA RNAME: admin email in DNS format (admin.example.com.)
        $adminEmail = 'admin.' . rtrim($domain->domain, '.') . '.';

        $serial = $this->generateSerial($domain->domain);

        $records = DnsRecord::where('domain_id', $domain->id)->get();

        $zone = "; BIND Zone file for {$domain->domain}\n";
        $zone .= "; Generated by QIWHOST Panel on " . date('Y-m-d H:i:s') . "\n";
        $zone .= "; DO NOT EDIT MANUALLY — managed by QIWHOST Panel\n\n";

        $zone .= "\$TTL 3600\n";
        $zone .= "@   IN  SOA {$ns1Fqdn} {$adminEmail} (\n";
        $zone .= "          {$serial}  ; Serial\n";
        $zone .= "          3600       ; Refresh\n";
        $zone .= "          1800       ; Retry\n";
        $zone .= "          604800     ; Expire\n";
        $zone .= "          86400 )    ; Minimum TTL\n\n";

        // Nameserver records from SOA
        $zone .= "; Nameservers\n";
        $zone .= "@   IN  NS  {$ns1Fqdn}\n";
        $zone .= "@   IN  NS  {$ns2Fqdn}\n\n";

        // User-defined records from database
        $zone .= "; Zone Records\n";

        foreach ($records as $rec) {
            $name = str_pad($rec->name, 20, ' ');
            $ttl = str_pad($rec->ttl, 8, ' ');
            $type = str_pad($rec->type, 8, ' ');

            $value = $rec->value;
            // TXT records must be quoted in zone files
            if ($rec->type === 'TXT' && !str_starts_with($value, '"')) {
                $value = '"' . $value . '"';
            }

            // MX and SRV need priority before value
            if ($rec->priority !== null && in_array($rec->type, ['MX', 'SRV'])) {
                $zone .= "{$name} {$ttl} IN  {$type} {$rec->priority}  {$value}\n";
            } else {
                $zone .= "{$name} {$ttl} IN  {$type} {$value}\n";
            }
        }

        return $zone;
    }

    /**
     * Sync a single domain's DNS zone to BIND
     */
    public function syncZone(int $domainId): bool
    {
        try {
            $domain = Domain::find($domainId);
            if (!$domain) return false;

            // Ensure zone directory exists
            $mkdirProc = new Process(['sudo', 'mkdir', '-p', $this->zoneDir]);
            $mkdirProc->run();

            // Compile zone file content
            $zoneContent = $this->compileZoneFile($domain);

            // Write zone file to temp location, then move securely
            $tmpFile = "/tmp/bind_zone_{$domain->domain}_" . uniqid() . '.db';
            file_put_contents($tmpFile, $zoneContent);

            $zoneFilePath = "{$this->zoneDir}/{$domain->domain}.db";
            $mvProc = new Process(['sudo', 'mv', $tmpFile, $zoneFilePath]);
            $mvProc->run();

            // Set ownership to bind:bind
            $chownProc = new Process(['sudo', 'chown', 'bind:bind', $zoneFilePath]);
            $chownProc->run();

            $chmodProc = new Process(['sudo', 'chmod', '644', $zoneFilePath]);
            $chmodProc->run();

            // Register zone in named.conf.local if not already present
            $this->registerZone($domain->domain);

            // Reload BIND
            $this->reloadBind();

            return true;
        } catch (\Exception $e) {
            \Log::warning("DnsZoneSyncService::syncZone failed for domain_id={$domainId}: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Register a zone in named.conf.local
     */
    private function registerZone(string $domainName): void
    {
        try {
            // Check if zone is already registered
            if (file_exists($this->namedConfLocal)) {
                $conf = file_get_contents($this->namedConfLocal);
                if (strpos($conf, "zone \"{$domainName}\"") !== false) {
                    return; // Already registered
                }
            }

            $zoneBlock = "\nzone \"{$domainName}\" {\n";
            $zoneBlock .= "    type master;\n";
            $zoneBlock .= "    file \"{$this->zoneDir}/{$domainName}.db\";\n";
            $zoneBlock .= "    allow-transfer { none; };\n";
            $zoneBlock .= "};\n";

            // Append to named.conf.local
            $tmpFile = '/tmp/named_conf_local_' . uniqid();
            $currentContent = file_exists($this->namedConfLocal) ? file_get_contents($this->namedConfLocal) : '';
            file_put_contents($tmpFile, $currentContent . $zoneBlock);

            $mvProc = new Process(['sudo', 'mv', $tmpFile, $this->namedConfLocal]);
            $mvProc->run();

            $chownProc = new Process(['sudo', 'chown', 'root:bind', $this->namedConfLocal]);
            $chownProc->run();
        } catch (\Exception $e) {
            \Log::warning("DnsZoneSyncService::registerZone failed for {$domainName}: " . $e->getMessage());
        }
    }

    /**
     * Remove a zone from BIND (zone file + named.conf.local entry)
     */
    public function removeZone(string $domainName): bool
    {
        try {
            // Remove zone file
            $zoneFilePath = "{$this->zoneDir}/{$domainName}.db";
            $rmProc = new Process(['sudo', 'rm', '-f', $zoneFilePath]);
            $rmProc->run();

            // Remove zone block from named.conf.local
            if (file_exists($this->namedConfLocal)) {
                $conf = file_get_contents($this->namedConfLocal);
                // Remove the zone block using regex
                $pattern = '/\n?zone\s+"' . preg_quote($domainName, '/') . '"\s+\{[^}]*\};\s*/';
                $newConf = preg_replace($pattern, '', $conf);
                
                if ($newConf !== $conf) {
                    $tmpFile = '/tmp/named_conf_local_' . uniqid();
                    file_put_contents($tmpFile, $newConf);
                    $mvProc = new Process(['sudo', 'mv', $tmpFile, $this->namedConfLocal]);
                    $mvProc->run();
                }
            }

            // Reload BIND
            $this->reloadBind();

            return true;
        } catch (\Exception $e) {
            \Log::warning("DnsZoneSyncService::removeZone failed for {$domainName}: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Reload BIND9 to apply zone changes
     */
    private function reloadBind(): void
    {
        try {
            // Try rndc reload first (graceful)
            $proc = new Process(['sudo', 'rndc', 'reload']);
            $proc->setTimeout(10);
            $proc->run();

            if (!$proc->isSuccessful()) {
                // Fallback to systemctl restart
                $proc2 = new Process(['sudo', 'systemctl', 'reload', 'named']);
                $proc2->setTimeout(10);
                $proc2->run();
            }
        } catch (\Exception $e) {
            // Silent fail on dev environments where BIND isn't installed
        }
    }

    /**
     * Provision default DNS records for a new domain
     * Includes A, www, NS, MX, mail, SPF, DMARC, and DKIM records
     */
    public static function provisionDefaultRecords(Domain $domain): void
    {
        $service = new self();
        [$ns1, $ns2] = $service->getNameservers();
        $serverIp = $service->getServerIp();

        $defaultRecords = [
            // Root A record → server IP
            ['name' => '@', 'type' => 'A', 'value' => $serverIp, 'ttl' => 3600, 'priority' => null],
            // www CNAME → root domain
            ['name' => 'www', 'type' => 'CNAME', 'value' => $domain->domain . '.', 'ttl' => 3600, 'priority' => null],
            // NS records
            ['name' => '@', 'type' => 'NS', 'value' => rtrim($ns1, '.') . '.', 'ttl' => 86400, 'priority' => null],
            ['name' => '@', 'type' => 'NS', 'value' => rtrim($ns2, '.') . '.', 'ttl' => 86400, 'priority' => null],
            // Mail server
            ['name' => '@', 'type' => 'MX', 'value' => 'mail.' . $domain->domain . '.', 'ttl' => 3600, 'priority' => 10],
            ['name' => 'mail', 'type' => 'A', 'value' => $serverIp, 'ttl' => 3600, 'priority' => null],
            // Default SPF — allow the server IP, MX records, and the domain's A record
            ['name' => '@', 'type' => 'TXT', 'value' => 'v=spf1 a mx ip4:' . $serverIp . ' ~all', 'ttl' => 3600, 'priority' => null],
            // DMARC — default policy: quarantine with aggregate reports
            ['name' => '_dmarc', 'type' => 'TXT', 'value' => 'v=DMARC1; p=quarantine; sp=quarantine; adkim=r; aspf=r; pct=100; fo=1', 'ttl' => 3600, 'priority' => null],
        ];

        foreach ($defaultRecords as $rec) {
            DnsRecord::create(array_merge($rec, ['domain_id' => $domain->id]));
        }

        // Generate DKIM key and create DNS record
        $dkimPublicKey = $service->generateDkimKey($domain->domain);
        if ($dkimPublicKey) {
            DnsRecord::create([
                'domain_id' => $domain->id,
                'name' => 'mail._domainkey',
                'type' => 'TXT',
                'value' => $dkimPublicKey,
                'ttl' => 3600,
                'priority' => null,
            ]);
        }

        // Sync the zone to BIND
        $service->syncZone($domain->id);
    }

    /**
     * Generate DKIM key pair for a domain using opendkim-genkey
     * Returns the public key value for DNS TXT record, or null on failure
     */
    public function generateDkimKey(string $domainName): ?string
    {
        try {
            $keyDir = "/etc/opendkim/keys/{$domainName}";
            $selector = 'mail';

            // Create key directory
            $mkdirProc = new Process(['sudo', 'mkdir', '-p', $keyDir]);
            $mkdirProc->run();

            // Check if key already exists
            $checkProc = new Process(['sudo', 'test', '-f', "{$keyDir}/{$selector}.private"]);
            $checkProc->run();

            if (!$checkProc->isSuccessful()) {
                // Generate new DKIM key pair (2048-bit RSA)
                $genProc = new Process([
                    'sudo', 'opendkim-genkey',
                    '-b', '2048',
                    '-d', $domainName,
                    '-D', $keyDir,
                    '-s', $selector,
                    '-v'
                ]);
                $genProc->setTimeout(30);
                $genProc->run();

                if (!$genProc->isSuccessful()) {
                    \Log::warning("DKIM key generation failed for {$domainName}: " . $genProc->getErrorOutput());
                    return null;
                }

                // Set ownership so OpenDKIM can read the private key
                $chownProc = new Process(['sudo', 'chown', '-R', 'opendkim:opendkim', $keyDir]);
                $chownProc->run();

                $chmodProc = new Process(['sudo', 'chmod', '600', "{$keyDir}/{$selector}.private"]);
                $chmodProc->run();
            }

            // Read the public key DNS record from the generated .txt file
            $readProc = new Process(['sudo', 'cat', "{$keyDir}/{$selector}.txt"]);
            $readProc->run();
            $rawTxt = $readProc->getOutput();

            // Parse the public key value from the TXT record
            // Format: mail._domainkey IN TXT ( "v=DKIM1; ..." "p=..." )
            $publicKey = $this->parseDkimPublicKey($rawTxt);

            if ($publicKey) {
                // Update OpenDKIM configuration tables
                $this->updateOpenDkimTables($domainName, $selector, $keyDir);
            }

            return $publicKey;
        } catch (\Exception $e) {
            \Log::warning("DnsZoneSyncService::generateDkimKey failed for {$domainName}: " . $e->getMessage());
            return null;
        }
    }

    /**
     * Parse the public key from opendkim-genkey output .txt file
     */
    private function parseDkimPublicKey(string $rawTxt): ?string
    {
        if (empty($rawTxt)) return null;

        // Extract all quoted strings and concatenate them
        preg_match_all('/"([^"]*)"/', $rawTxt, $matches);

        if (empty($matches[1])) return null;

        // Join all quoted parts into a single DNS TXT value
        $combined = implode('', $matches[1]);

        // Clean up whitespace
        $combined = preg_replace('/\s+/', ' ', trim($combined));

        return $combined;
    }

    /**
     * Update OpenDKIM's KeyTable, SigningTable, and TrustedHosts
     * so it knows to sign outgoing mail for this domain
     */
    private function updateOpenDkimTables(string $domainName, string $selector, string $keyDir): void
    {
        try {
            $keyTableFile = '/etc/opendkim/KeyTable';
            $signingTableFile = '/etc/opendkim/SigningTable';
            $trustedHostsFile = '/etc/opendkim/TrustedHosts';

            // KeyTable entry: selector._domainkey.domain domain:selector:/path/to/key
            $keyEntry = "{$selector}._domainkey.{$domainName} {$domainName}:{$selector}:{$keyDir}/{$selector}.private";

            // SigningTable entry: *@domain selector._domainkey.domain
            $sigEntry = "*@{$domainName} {$selector}._domainkey.{$domainName}";

            // Append to KeyTable if not already present
            $checkKey = new Process(['sudo', 'grep', '-qF', $domainName, $keyTableFile]);
            $checkKey->run();
            if (!$checkKey->isSuccessful()) {
                $appendKey = new Process(['sudo', 'bash', '-c', "echo '{$keyEntry}' >> {$keyTableFile}"]);
                $appendKey->run();
            }

            // Append to SigningTable if not already present
            $checkSig = new Process(['sudo', 'grep', '-qF', $domainName, $signingTableFile]);
            $checkSig->run();
            if (!$checkSig->isSuccessful()) {
                $appendSig = new Process(['sudo', 'bash', '-c', "echo '{$sigEntry}' >> {$signingTableFile}"]);
                $appendSig->run();
            }

            // Append to TrustedHosts if not already present
            $checkTrusted = new Process(['sudo', 'grep', '-qF', $domainName, $trustedHostsFile]);
            $checkTrusted->run();
            if (!$checkTrusted->isSuccessful()) {
                $appendTrusted = new Process(['sudo', 'bash', '-c', "echo '{$domainName}' >> {$trustedHostsFile}"]);
                $appendTrusted->run();
            }

            // Reload OpenDKIM to pick up new keys
            $reloadProc = new Process(['sudo', 'systemctl', 'restart', 'opendkim']);
            $reloadProc->setTimeout(10);
            $reloadProc->run();
        } catch (\Exception $e) {
            \Log::warning("OpenDKIM table update failed for {$domainName}: " . $e->getMessage());
        }
    }

    /**
     * One-time setup: Configure Postfix ↔ OpenDKIM integration
     * and set OpenDKIM to use KeyTable/SigningTable mode
     * Call this once during installation or via artisan command
     */
    public static function setupOpenDkimPostfixIntegration(): void
    {
        try {
            // 1. Configure opendkim.conf for multi-domain signing
            $opendkimConf = <<<'CONF'
Syslog              yes
SyslogSuccess       yes
Canonicalization    relaxed/simple
Mode                sv
SubDomains          no
OversignHeaders     From

# Multi-domain key management
KeyTable            /etc/opendkim/KeyTable
SigningTable        refile:/etc/opendkim/SigningTable
ExternalIgnoreList  /etc/opendkim/TrustedHosts
InternalHosts       /etc/opendkim/TrustedHosts

UserID              opendkim
UMask               007
Socket              inet:8891@localhost
PidFile             /run/opendkim/opendkim.pid
CONF;

            $tempConf = '/tmp/opendkim_conf_' . uniqid();
            file_put_contents($tempConf, $opendkimConf);

            $mvProc = new Process(['sudo', 'mv', $tempConf, '/etc/opendkim.conf']);
            $mvProc->run();

            $chownProc = new Process(['sudo', 'chown', 'root:root', '/etc/opendkim.conf']);
            $chownProc->run();

            // 2. Create empty table files if they don't exist
            foreach (['KeyTable', 'SigningTable', 'TrustedHosts'] as $file) {
                $path = "/etc/opendkim/{$file}";
                $touchProc = new Process(['sudo', 'bash', '-c', "[ -f {$path} ] || touch {$path}"]);
                $touchProc->run();

                $chownProc = new Process(['sudo', 'chown', 'opendkim:opendkim', $path]);
                $chownProc->run();
            }

            // Initialize TrustedHosts with localhost entries
            $checkTH = new Process(['sudo', 'grep', '-qF', '127.0.0.1', '/etc/opendkim/TrustedHosts']);
            $checkTH->run();
            if (!$checkTH->isSuccessful()) {
                $initTH = new Process(['sudo', 'bash', '-c', "printf '127.0.0.1\nlocalhost\n' >> /etc/opendkim/TrustedHosts"]);
                $initTH->run();
            }

            // 3. Configure Postfix to use OpenDKIM milter
            $postfixCmds = [
                ['sudo', 'postconf', '-e', 'milter_protocol = 6'],
                ['sudo', 'postconf', '-e', 'milter_default_action = accept'],
                ['sudo', 'postconf', '-e', 'smtpd_milters = inet:localhost:8891'],
                ['sudo', 'postconf', '-e', 'non_smtpd_milters = inet:localhost:8891'],
            ];

            foreach ($postfixCmds as $cmd) {
                $proc = new Process($cmd);
                $proc->run();
            }

            // 4. Restart services
            $restartDkim = new Process(['sudo', 'systemctl', 'restart', 'opendkim']);
            $restartDkim->run();

            $restartPostfix = new Process(['sudo', 'systemctl', 'restart', 'postfix']);
            $restartPostfix->run();

            \Log::info("OpenDKIM ↔ Postfix integration configured successfully.");
        } catch (\Exception $e) {
            \Log::warning("OpenDKIM-Postfix setup failed: " . $e->getMessage());
        }
    }
}

